language: node_js

branches:
  only:
  - master

before_script:
  - npm install -g uglify-js

script: uglifyjs simple-popup.js --compress --mangle --output simple-popup.min.js

notifications:
  email: false